# supabase/config.toml

# A string used to distinguish different Supabase projects on the same host.
project_id = "psychometric-assessment-platform"

# This is the reference to your cloud project
project_ref = "sayftcijqhnpzlznvqcz"